# Generated by Django 4.2.10 on 2024-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
